#
###################################
# Site wide configuration
####################################
#
title: Caner Sahin
email: canersahin130@gmail.com
description: 
url: https://labicvl.github.io/caner # the base hostname & protocol for your site
keywords: ["Machine learning", "Computer Vision"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/London
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Caner Sahin
  avatar: caner.png
  job: ""
  bio: ""
  email: canersahin130@gmail.com
  disqus-shortname: 
  twitter: sahin_cnr #username
  facebook: #username
  google: #username
    plus: #username
    analytics: #UA-47703339-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #guiggh #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: caner-sahin-6870ab87 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  scholar: uMnRljAAAAAJ&hl=en #username
